Repository maheshjainckd/Hacktoberfest2022-for-everyone, pull requests merged in 2022-10, with the labels that each got.

#132 Django random password generator project
  web-development/randompassword/db.sqlite3
  web-development/randompassword/manage.py
  web-development/randompassword/randompassword/__init__.py
  web-development/randompassword/randompassword/__pycache__/__init__.cpython-38.pyc
  web-development/randompassword/randompassword/__pycache__/settings.cpython-38.pyc
  web-development/randompassword/randompassword/__pycache__/urls.cpython-38.pyc
  web-development/randompassword/randompassword/__pycache__/views.cpython-38.pyc
  web-development/randompassword/randompassword/__pycache__/wsgi.cpython-38.pyc
  web-development/randompassword/randompassword/asgi.py
  web-development/randompassword/randompassword/logic.py
  web-development/randompassword/randompassword/settings.py
  web-development/randompassword/randompassword/urls.py
  web-development/randompassword/randompassword/views.py
  web-development/randompassword/randompassword/wsgi.py
  web-development/randompassword/templates/contact.html
  web-development/randompassword/templates/index.html
  web-development/randompassword/templates/password.html
Labels: hacktoberfest-accepted, Hacktoberfest

#133 Famous book allocation problem.
  Java/Algorithms/BinarySearch/Book_Allocation.java
Labels: hacktoberfest-accepted, Hacktoberfest

#135 added operationsonlinkedlist.c
  C/operationsonlinkedlist.c
Labels: hacktoberfest-accepted, Hacktoberfest

#136 Create quick-sort.cpp
  CPP/quick-sort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#139 Created new Folder for computer graphics
  C/ComputerGraphic/Man_moving_in_rain.c
  C/ComputerGraphic/Mid_point_algorithm.c
  C/ComputerGraphic/README.md
Labels: hacktoberfest-accepted, Hacktoberfest

#144 Python guess number game
  Python/guess-num.py
  guess-num.py
Labels: hacktoberfest-accepted, Hacktoberfest

#145 Added Bubble Sort in Golang
  Golang/bubblesort.go
Labels: hacktoberfest-accepted, Hacktoberfest

#146 Testimonial added
  contributors.html
  web-development/Testimonial/Css/main.css
  web-development/Testimonial/Images/i1.jpeg
  web-development/Testimonial/Images/i2.jpeg
  web-development/Testimonial/Images/i3.jpeg
  web-development/Testimonial/Images/i4.jpeg
  web-development/Testimonial/index.html
Labels: hacktoberfest-accepted, Hacktoberfest

#259 checking for hacktoberfest activity
  CPP/LinkedList/reverseLL.cpp
Labels: question

#148 OOPS file with concepts and real world examples
  CPP/Bubble_sort.cpp
  OOPS.md
  contributors.html
Labels: hacktoberfest-accepted, Hacktoberfest

#154 Added file in java/algorithms
  Java/Algorithms/KadaneAlgo.java
Labels: hacktoberfest-accepted, Hacktoberfest

#155 Create ceil_bst.py
  Python/ceil_bst.py
Labels: hacktoberfest-accepted, Hacktoberfest

#157 added largestNumber in array
  Java/largestNumber.java
Labels: hacktoberfest-accepted, Hacktoberfest

#159 I have followed all the rules
  contributors.html
  dynamic-programming/MatrixChainMultiplication.java
Labels: hacktoberfest-accepted, Hacktoberfest

#160 Bouncing Ball Animation
  web-development/Bouncing-Ball/README.md
  web-development/Bouncing-Ball/bouncing-ball.html
Labels: hacktoberfest-accepted, Hacktoberfest

#161 added josephus problem solution in cpp
  CPP/josephus.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#162 Create topological_sorting_using_dfs
  CPP/topological_sorting_using_dfs.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#164 Added Decision Tree Regression in python and updated contributors.html
  Python/Decision_Tree_Regression.ipynb
  contributors.html
Labels: hacktoberfest-accepted, Hacktoberfest

#168 Created a flames game in cpp
  CPP/FLAMES.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#171 Create PowerOfXtoN.cpp
  CPP/PowerOfXtoN.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#176 Divyansh 003 patch 1
  Python/Palindrome_string.py
  Python/palindrome number
  Python/palindrome number.py
Labels: hacktoberfest-accepted, Hacktoberfest

#177 Create selection_sort.cpp
  CPP/selection_sort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#178 Reduced BinarySearch.cpp
  CPP/BinarySearch.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#182 Create pascalTriangle
  Python/pascalTriangle.py
Labels: hacktoberfest-accepted, Hacktoberfest

#189 Create Train_ticketing_sys.c
  C/Train_ticketing_sys.c
Labels: hacktoberfest-accepted, Hacktoberfest

#187 Create UnionOfTwo.cpp
  UnionOfTwo.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#412 Create LICENSE.md
  LICENSE.md
Labels: hacktoberfest-accepted, Hacktoberfest

#172 Add log base 10 value approximation with bisection program
  .github/FUNDING.yml
  Python/log10.py
  contributors.html
Labels: hacktoberfest-accepted, Hacktoberfest

#184 Added ArrayIntersection.java
  Java/ArrayIntersection.java
  contributors.html
Labels: hacktoberfest-accepted, Hacktoberfest

#253 Bank Management system using C Language
  C/Bank Management System/main.c
Labels: hacktoberfest-accepted, Hacktoberfest

#597 Added new Folder (PHP)
  PHP/Measurment/Styles.css
  PHP/Measurment/area.php
  PHP/Measurment/includes/functions.php
  PHP/Measurment/index.php
  PHP/Measurment/length.php
  PHP/Measurment/mass.php
  PHP/Measurment/speed.php
  PHP/Measurment/temperature.php
  PHP/Measurment/volume.php
  PHP/send mail in php/php_send_mail.php
  PHP/send mail in php/phpsendmail.html
  contributors.html
Labels: hacktoberfest-accepted

#468 Added Chrome Extension
  web-development/Chrome Extension/dollar.png
  web-development/Chrome Extension/index.css
  web-development/Chrome Extension/index.html
  web-development/Chrome Extension/index.js
  web-development/Chrome Extension/manifest.json
Labels: hacktoberfest-accepted

#680 Added JavaScript folder and Array Problems into it
  JavaScript/Array/Problems/Add_two_reverse.js
  JavaScript/Array/Problems/TwoSum.js
  JavaScript/Array/Problems/buildarray.perum.js
  JavaScript/Array/Problems/commonprefix.js
  JavaScript/Array/Problems/lengthoflastword.js
  JavaScript/Array/Problems/maxArea.js
  JavaScript/Array/Problems/palindrome.js
  JavaScript/Array/Problems/plusone.js
  JavaScript/Array/Problems/removeDuplicatesfromArray.js
  JavaScript/Array/Problems/removeElement.js
  JavaScript/Array/Problems/removeduplicate.js
  JavaScript/Array/Problems/reverseNumber.js
  JavaScript/Array/Problems/rotate2dmatrix.js
  JavaScript/Array/Problems/threesum.js
  JavaScript/Array/array.js
  JavaScript/Array/readme.md
  contributors.html
Labels: hacktoberfest-accepted

#776 Added a 6 boxes colour game
  contributors.html
  web-development/6box colour game/css/style.css
  web-development/6box colour game/index.html
  web-development/6box colour game/js/script.js
Labels: hacktoberfest-accepted

#143 Changed Permutation file
  CPP/Permutations.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#152 C program to calculate compound interest
  C/Calculate Compound Interest.c
Labels: hacktoberfest-accepted

#156 Create reverse_ll_kgroups.cpp
  CPP/reverse_ll_kgroups.cpp
Labels: hacktoberfest-accepted

#158 Create Create a sorted copy of a linked list.c
  C/Create a sorted copy of a linked list.c
Labels: hacktoberfest-accepted

#163 Create connected_components_using_dfs.cpp
  CPP/connected_components_using_dfs.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#179 Create Sequential_Serch.cpp
  CPP/Sequential_Serch.cpp
Labels: hacktoberfest-accepted

#193 Create bubbleSort.py
  Python/bubbleSort.py
Labels: hacktoberfest-accepted

#194 Create factorial.py
  Python/factorial.py
Labels: hacktoberfest-accepted

#196 Create quicksort.cpp
  CPP/LinkedList/quicksort.cpp
Labels: hacktoberfest-accepted

#198 Armstrong.cpp
  CPP/Armstrong.cpp
Labels: hacktoberfest-accepted

#199 added program for binary tree inorder traversal
  CPP/binary-tree-inorder-traversal.cpp
Labels: hacktoberfest-accepted

#396 Update README.md
  README.md
Labels: hacktoberfest-accepted

#202 Added program on the based of Linked List in java .
  Java/linkedList/AddTwoNumberInLL.java
  Java/linkedList/MergeTwoSortedLinkedList.java
  Java/linkedList/ReverseNodeInKGroup.java
  Java/linkedList/createBinaryTreeWithInOrderTraversal.java
  Java/linkedList/removeNthNodeFromEnd.java
  Java/linkedList/swapTwoNumberInLL.java
Labels: hacktoberfest-accepted, Hacktoberfest

#203 Create reverse_string.cpp
  CPP/reverse_string.cpp
Labels: hacktoberfest-accepted

#205 Create stringPalindromeCheck.py
  Python/stringPalindromeCheck.py
Labels: hacktoberfest-accepted

#208 max and min in an array added
  CPP/Max_Min.cpp
Labels: hacktoberfest-accepted

#214 Create Longest_Palindromic_Substring.cpp
  CPP/Longest_Palindromic_Substring.cpp
Labels: hacktoberfest-accepted

#216 added c program
  C/half_pyramid.c
  contributors.html
Labels: hacktoberfest-accepted

#223 Sorted Singly Linked List in cpp
  CPP/LinkedList/SortedSinglyLinkedList.cpp
  CPP/SortedSinglyLinkedList.cpp
Labels: hacktoberfest-accepted

#225 Create Longest_Common_Subsequence.cpp
  CPP/Longest_Common_Subsequence.cpp
  web-development/Food Delievery Website/1.jpg
  web-development/Food Delievery Website/2.jpg
  web-development/Food Delievery Website/3.jpg
  web-development/Food Delievery Website/4.jpg
  web-development/Food Delievery Website/Tut39.css
  web-development/Food Delievery Website/Tut39.html
  web-development/Food Delievery Website/logo.png
Labels: hacktoberfest-accepted

#226 Added Permutation_Combination.cpp program in CPP folder
  CPP/Permutation_Combination.cpp
  contributors.html
Labels: hacktoberfest-accepted

#238 Create PrimeNumber.c
  C/PrimeNumber.c
Labels: hacktoberfest-accepted

#245 Added Quick Sort Algorithm in C++
  CPP/.vscode/settings.json
  CPP/quickSort.cpp
Labels: hacktoberfest-accepted

#247 Create reverse-a-linked-list.cpp
  CPP/reverse-a-linked-list.cpp
Labels: hacktoberfest-accepted

#248 Added Array Listing Java
  Java/Array/Swap_two_nodes.java
  Java/Array/reverseLL.java
  Java/Array/rightviewofbinarytree.java
Labels: hacktoberfest-accepted

#250 Boruvka's Algorithm for Minimum Spanning Tree
  CPP/boruvka_algo.cpp
Labels: hacktoberfest-accepted

#801 add react app
  React JS/.gitignore
  React JS/README.md
  React JS/package-lock.json
  React JS/package.json
  React JS/public/favicon.ico
  React JS/public/index.html
  React JS/public/logo192.png
  React JS/public/logo512.png
  React JS/public/manifest.json
  React JS/public/robots.txt
  React JS/src/App.css
  React JS/src/App.js
  React JS/src/App.test.js
  React JS/src/components/Navbar.jsx
  React JS/src/components/Routes.jsx
  React JS/src/components/TodoCard.jsx
  React JS/src/components/TodoDetailCard.jsx
  React JS/src/components/TodoForm.jsx
  React JS/src/components/UpdateForm.jsx
  React JS/src/context.js
  React JS/src/data.js
  React JS/src/index.css
  React JS/src/index.js
  React JS/src/logo.svg
  React JS/src/pages/CreateTodo.jsx
  React JS/src/pages/Detail.jsx
  React JS/src/pages/Home.jsx
  React JS/src/pages/NotFound.jsx
  React JS/src/reportWebVitals.js
  React JS/src/setupTests.js
  contributors.html
Labels: hacktoberfest-accepted

#251 added chinese Remainder Theorem
  CPP/Chinese Remainder Theorem.cpp
Labels: hacktoberfest-accepted

#252 Hierholzer algorithm in C++
  CPP/Hierholzer_algo.cpp
Labels: hacktoberfest-accepted

#261 Create FirstBadVersion.java
  Java/Algorithms/BinarySearch/FirstBadVersion.java
Labels: hacktoberfest-accepted

#262 Flatten a binary Tree to Linked List
  CPP/Flatten_a_binary_tree.cpp
Labels: hacktoberfest-accepted

#264 Create anagram.cpp
  CPP/anagram.cpp
Labels: hacktoberfest-accepted

#266 Insertion_sort_InnocentDaksh63.java
  Java/Insertion_Sort.java
Labels: hacktoberfest-accepted

#269 half_star_pattern in python
  Python/half_star_pattern.py
Labels: hacktoberfest-accepted

#273 Deleting_Node_Linked_List.cpp
  CPP/LinkedList/Deleting_Node_Linked_List.cpp
Labels: hacktoberfest-accepted

#277 Create eliminateVowels.cpp
  CPP/eliminateVowels.cpp
Labels: hacktoberfest-accepted

#280 added inorder.cpp
  CPP/inorder.cpp
Labels: hacktoberfest-accepted

#284 added kruskal's algorithm
  CPP/kruskal_algorithm.cpp
Labels: hacktoberfest-accepted

#288 added prim's algorithm
  CPP/primAlgorithm.cpp
Labels: hacktoberfest-accepted

#291 added dijkstra's algorithm
  CPP/dijkstraAlgorithm.cpp
Labels: hacktoberfest-accepted

#292 Create Search_a_2D_Matrix.cpp
  CPP/Search_a_2D_Matrix.cpp
Labels: hacktoberfest-accepted

#293 kruskal algo.cpp file in graph directory
  CPP/Graphs/kruskal_algo.cpp
  contributors.html
Labels: hacktoberfest-accepted

#294 added bitonic sort
  CPP/bitonic_sort.cpp
Labels: hacktoberfest-accepted

#298 bitonic sort in python
  Python/Bitonic_Sort.py
Labels: hacktoberfest-accepted

#308 Create LongestCommonSubsequence.py
  Python/LongestCommonSubsequence.py
Labels: hacktoberfest-accepted

#309 Update Pigeonhole_sort.cpp
  CPP/Pigeonhole_sort.cpp
Labels: hacktoberfest-accepted

#310 C++ programs added and Updated Contributors.html
  CPP/Area.cpp
  CPP/Matrix.cpp
  contributors.html
Labels: hacktoberfest-accepted

#311 create nltk_project.py
  Python/nltk_project.py
Labels: hacktoberfest-accepted

#313 Added My Python Code
  Python/Rock,Paper,Scissors.py
Labels: hacktoberfest-accepted

#315 Create Binary Search Tree(BST).cpp
  CPP/Binary Search Tree(BST).cpp
Labels: hacktoberfest-accepted

#318 Selection sort.c
  CPP/selection sort.cpp
Labels: hacktoberfest-accepted

#319 Create Columnar_cipher
  CPP/Columnar_cipher
Labels: hacktoberfest-accepted

#321 Quadratic equations solver
  Java/quadraticEq.java
Labels: hacktoberfest-accepted

#322 Question added in stack
  CPP/stack/Valid_Parentheses.cpp
Labels: hacktoberfest-accepted

#330 Create Three_Way_Partition.cpp
  CPP/Three_Way_Partition.cpp
Labels: hacktoberfest-accepted

#339 Matrix multiplication.c
  C/Matrix multiplication.c
Labels: hacktoberfest-accepted

#341 added rat-in-a-maze program in c++
  CPP/rat-in-a-maze.cpp
Labels: hacktoberfest-accepted

#344 Number Triangle.cpp
  CPP/Number Triangle.cpp
Labels: hacktoberfest-accepted

#346 added code for binary trees in C++
  CPP/binary tree/BT to LL using stack.cpp
  CPP/binary tree/bottom view.cpp
  CPP/binary tree/diagonal traversal.cpp
  CPP/binary tree/level order traversal.cpp
  CPP/binary tree/minimum swaps bt to bst.cpp
  CPP/binary tree/right view left view.cpp
  CPP/binary tree/topView.cpp
  CPP/binary tree/zigzag traversal.cpp
Labels: hacktoberfest-accepted

#348 Created scroll up and scroll down button
  web-development/button.html
Labels: hacktoberfest-accepted

#351 Bubble Sort
  CPP/bubblesort.cpp
Labels: hacktoberfest-accepted

#736 Made a JSX object transpiler with DOM rendering .
  web-development/ES6-7-jsx-transpiler/index.html
  web-development/ES6-7-jsx-transpiler/index.js
Labels: hacktoberfest-accepted

#967 Added bank Managment System Web Application
  web-development/BankAppliation/.gitignore
  web-development/BankAppliation/README.md
  web-development/BankAppliation/package-lock.json
  web-development/BankAppliation/package.json
  web-development/BankAppliation/public/_redirects
  web-development/BankAppliation/public/index.html
  web-development/BankAppliation/public/manifest.json
  web-development/BankAppliation/src/App.js
  web-development/BankAppliation/src/Firebase.js
  web-development/BankAppliation/src/components/pages/Demo.js
  web-development/BankAppliation/src/components/pages/Deposite.js
  web-development/BankAppliation/src/components/pages/Error.js
  web-development/BankAppliation/src/components/pages/History.js
  web-development/BankAppliation/src/components/pages/Home.js
  web-development/BankAppliation/src/components/pages/Login.js
  web-development/BankAppliation/src/components/pages/Register.js
  web-development/BankAppliation/src/components/pages/Users.js
  web-development/BankAppliation/src/components/widgets/Footer.js
  web-development/BankAppliation/src/components/widgets/Navbar.js
  web-development/BankAppliation/src/components/widgets/Particles.js
  web-development/BankAppliation/src/components/widgets/TextChanger.js
  web-development/BankAppliation/src/images/bank.png
  web-development/BankAppliation/src/images/bank_2.png
  web-development/BankAppliation/src/images/banklogo.png
  web-development/BankAppliation/src/images/bars.png
  web-development/BankAppliation/src/images/bars_solid.svg
  web-development/BankAppliation/src/images/bhau.png
  web-development/BankAppliation/src/images/credit-card.png
  web-development/BankAppliation/src/images/museum.png
  web-development/BankAppliation/src/images/wave.png
  web-development/BankAppliation/src/images/wave2.png
  web-development/BankAppliation/src/index.js
  web-development/BankAppliation/src/styles/App.css
  web-development/BankAppliation/src/styles/Demo.css
  web-development/BankAppliation/src/styles/Deposite.css
  web-development/BankAppliation/src/styles/Error.css
  web-development/BankAppliation/src/styles/Footer.css
  web-development/BankAppliation/src/styles/History.css
  web-development/BankAppliation/src/styles/Home.css
  web-development/BankAppliation/src/styles/Login.css
  web-development/BankAppliation/src/styles/Navbar.css
  web-development/BankAppliation/src/styles/Register.css
  web-development/BankAppliation/src/styles/Text.css
  web-development/BankAppliation/src/styles/Users.css
  web-development/BankAppliation/yarn.lock
Labels: hacktoberfest-accepted

#965 php dice game
  PHP/send mail in php/dicegame.php
  contributors.html
Labels: hacktoberfest-accepted
